/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthButton: typeof import('./../src/views/auth/components/AuthButton.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    CustomCheckbox: typeof import('./../src/views/example-view/custom-checkbox/components/CustomCheckbox.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ExampleCssClamp: typeof import('./../src/views/example-view/css-features/components/ExampleCssClamp.vue')['default']
    ExampleCssContainerQuery: typeof import('./../src/views/example-view/css-features/components/ExampleCssContainerQuery.vue')['default']
    ExampleCssContainerStyle: typeof import('./../src/views/example-view/css-features/components/ExampleCssContainerStyle.vue')['default']
    ExampleCssGradient: typeof import('./../src/views/example-view/css-features/components/ExampleCssGradient.vue')['default']
    ExampleCssNestingBind: typeof import('./../src/views/example-view/css-features/components/ExampleCssNestingBind.vue')['default']
    ExampleCssScroll: typeof import('./../src/views/example-view/css-features/components/ExampleCssScroll.vue')['default']
    ExampleCssSelectElement: typeof import('./../src/views/example-view/css-features/components/ExampleCssSelectElement.vue')['default']
    ExampleCssText: typeof import('./../src/views/example-view/css-features/components/ExampleCssText.vue')['default']
    ExampleCssViewport: typeof import('./../src/views/example-view/css-features/components/ExampleCssViewport.vue')['default']
    ExampleViewComponent: typeof import('./../src/views/example-view/components/ExampleViewComponent.vue')['default']
    FF: typeof import('./../src/components/FF.vue')['default']
    GeneralExampleComponent: typeof import('./../src/views/example-view/general/components/GeneralExampleComponent.vue')['default']
    Header: typeof import('./../src/components/layout/Header.vue')['default']
    IconCar: typeof import('~icons/icon/car')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    IconCheckFilled: typeof import('~icons/icon/check-filled')['default']
    IconDoubleArrow: typeof import('~icons/icon/double-arrow')['default']
    ItemObserver: typeof import('./../src/views/example-view/components/ItemObserver.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../src/components/layout/Sidebar.vue')['default']
    TelegramAlert: typeof import('./../src/views/telegram/components/TelegramAlert.vue')['default']
    TelegramBackButton: typeof import('./../src/views/telegram/components/TelegramBackButton.vue')['default']
    TelegramBiometricManager: typeof import('./../src/views/telegram/components/TelegramBiometricManager.vue')['default']
    TelegramClosingConfirmation: typeof import('./../src/views/telegram/components/TelegramClosingConfirmation.vue')['default']
    TelegramConfirm: typeof import('./../src/views/telegram/components/TelegramConfirm.vue')['default']
    TelegramExpandedViewport: typeof import('./../src/views/telegram/components/TelegramExpandedViewport.vue')['default']
    TelegramMainButton: typeof import('./../src/views/telegram/components/TelegramMainButton.vue')['default']
    TelegramPopup: typeof import('./../src/views/telegram/components/TelegramPopup.vue')['default']
    TelegramUseWebApp: typeof import('./../src/views/telegram/components/TelegramUseWebApp.vue')['default']
    TestComponent: typeof import('./../src/views/example-view/components/TestComponent.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
